package mbg.entity;

public class Mybatistest extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatistest.id
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatistest.desc_m
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    private String descM;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatistest.id
     *
     * @return the value of mybatistest.id
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatistest.id
     *
     * @param id the value for mybatistest.id
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatistest.desc_m
     *
     * @return the value of mybatistest.desc_m
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    public String getDescM() {
        return descM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatistest.desc_m
     *
     * @param descM the value for mybatistest.desc_m
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    public void setDescM(String descM) {
        this.descM = descM;
    }
}