package mbg.mapper;

import java.util.List;
import mbg.entity.Mybatistest;

public interface MybatistestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatistest
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatistest
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    int insert(Mybatistest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatistest
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    Mybatistest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatistest
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    List<Mybatistest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatistest
     *
     * @mbg.generated Mon May 26 13:40:38 CST 2025
     */
    int updateByPrimaryKey(Mybatistest record);
}